@@include('main__nav.js')
@@include('webp.js')
@@include('../../node_modules/swiper/swiper-bundle.js')
@@include('swiper.js')
@@include('anchor-scroll.js')
@@include('counter.js')
@@include('dates.js')
// Libs
// @@include('wow.min.js')
@@include('../../node_modules/wow.js/dist/wow.js')
@@include('wow-init.js')