@@include('main__nav.js')
@@include('webp.js')
@@include('swiper-bundle.min.js')
@@include('swiper.js')
@@include('anchor-scroll.js')
@@include('counter.js')
@@include('dates.js')
@@include('lazy-ivan.js')
@@include('video__fix.js')
// Libs
@@include('wow.min.js')
@@include('wow-init.js')